/**
 * Status Constants
 * Defines all status enums for the application
 */

// Attendance Status
const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  HALF_DAY: 'HALF_DAY',
  LEAVE: 'LEAVE',
  SICK_LEAVE: 'SICK_LEAVE',
  WORK_FROM_HOME: 'WORK_FROM_HOME',
};

// Student Status
const STUDENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  GRADUATED: 'GRADUATED',
  TRANSFERRED: 'TRANSFERRED',
  SUSPENDED: 'SUSPENDED',
  EXPELLED: 'EXPELLED',
  LEFT: 'LEFT',
  ON_LEAVE: 'ON_LEAVE',
};

// User Status
const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  BLOCKED: 'BLOCKED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
};

// Class Status
const CLASS_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ARCHIVED: 'ARCHIVED',
  DRAFT: 'DRAFT',
};

// Exam Status
const EXAM_STATUS = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  PUBLISHED: 'PUBLISHED',
};

// Fee Status
const FEE_STATUS = {
  PAID: 'PAID',
  PENDING: 'PENDING',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  OVERDUE: 'OVERDUE',
  EXEMPTED: 'EXEMPTED',
  CANCELLED: 'CANCELLED',
};

// Grade Status
const GRADE_STATUS = {
  DRAFTED: 'DRAFTED',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
};

// Leave Status
const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

// Document Status
const DOCUMENT_STATUS = {
  PENDING: 'PENDING',
  GENERATED: 'GENERATED',
  ISSUED: 'ISSUED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
};

// Export for ES modules
export {
  ATTENDANCE_STATUS,
  STUDENT_STATUS,
  USER_STATUS,
  CLASS_STATUS,
  EXAM_STATUS,
  FEE_STATUS,
  GRADE_STATUS,
  LEAVE_STATUS,
  DOCUMENT_STATUS,
};
